NET_TIMER_SET = 1
NET_TIMER_TOGGLE = 2
NET_TIMER_NETDATATIME = 3

NET_TEXT_CENTERMESSAGE = 1
NET_TEXT_DISPLAYNOTIFY = 2
NET_TEXT_COLOREDMESSAGE = 3

NET_VARS_REQUEST = 1
NET_VARS_SEND = 2

NET_PLAYERVARS_SEND = 1

NET_GAMEVOTES_OPEN = 1
NET_GAMEVOTES_CLOSE = 2
NET_GAMEVOTES_VOTE = 3
NET_GAMEVOTES_ADD = 4
NET_GAMEVOTES_REMOVE = 5

NET_MAPVOTES_OPEN = 1
NET_MAPVOTES_CLOSE = 2
NET_MAPVOTES_VOTE = 3
NET_MAPVOTES_ADD = 4
NET_MAPVOTES_REMOVE = 5

NET_TEAMS_CLEAR = 1
NET_TEAMS_ADD = 2

NET_PLAYER_SENDDEATHTIME = 1

NET_WORLD_MAKEPERSISTENT = 1
NET_WORLD_REMOVEPERSISTENCE = 2
NET_WORLD_MAKERESPAWNABLE = 3
NET_WORLD_REMOVERESPAWNABLE = 4

NET_MISC_INITIALIZEPLAYER = 1
NET_MISC_TRIGGERPARTICLES = 2
NET_MISC_TRIGGERENDGAMEMUSIC = 3

NET_STATS_SENDSTAT = 1